export default {
  app_name: 'FutHub',
  see_all: 'See all',
  loading: 'Loading...',
  tab_home: 'Home',
  tab_favorites: 'Favorites',
  tab_ai: 'AI',
  tab_profile: 'Profile',
  live_matches: 'Live matches',
  tab_live: 'Live',
  tab_today: 'Today',
  tab_upcoming: 'Upcoming',
  ai_prediction: 'AI Prediction',
  win_probability: 'chance to win',
  tab_summary: 'Summary',
  tab_stats: 'Statistics',
  tab_events: 'Events',
  tab_ai_insights: 'AI Insights',
  possession: 'Possession',
  shots: 'Shots',
  shots_on_target: 'Shots on target',
  passes: 'Completed passes',
  fouls: 'Fouls',
  yellow_cards: 'Yellow cards',
  probabilities: 'PROBABILITIES',
  home_win: 'Home win',
  draw: 'Draw',
  away_win: 'Away win',
  ai_insight_text: 'The home team dominates midfield with 60% possession and has generated more dangerous opportunities. At this pace, they have a high probability of scoring another goal.',
  favorites_teams: 'Teams',
  favorites_competitions: 'Competitions',
  upcoming_matches: 'Upcoming matches',
  ia_placeholder: 'Type your question...',
  ia_quick_predictions: 'Predictions',
  ia_quick_curious: 'Fun facts',
  ia_quick_analysis: 'Quick analysis',
  ia_welcome: 'Hi! I am FutHub\'s AI assistant. Ask me about matches, statistics or predictions.',
};
