export default {
  app_name: 'FutHub',
  see_all: 'Ver todos',
  loading: 'Cargando...',
  tab_home: 'Inicio',
  tab_favorites: 'Favoritos',
  tab_ai: 'IA',
  tab_profile: 'Perfil',
  live_matches: 'Partidos en vivo',
  tab_live: 'En vivo',
  tab_today: 'Hoy',
  tab_upcoming: 'Próximos',
  ai_prediction: 'Predicción IA',
  win_probability: 'de ganar',
  tab_summary: 'Resumen',
  tab_stats: 'Estadísticas',
  tab_events: 'Eventos',
  tab_ai_insights: 'IA Insights',
  possession: 'Posesión',
  shots: 'Tiros',
  shots_on_target: 'Tiros a puerta',
  passes: 'Pases completados',
  fouls: 'Faltas',
  yellow_cards: 'Tarjetas amarillas',
  probabilities: 'PROBABILIDADES',
  home_win: 'Victoria local',
  draw: 'Empate',
  away_win: 'Victoria visitante',
  ai_insight_text: 'El equipo local domina el mediocampo con un 60% de posesión y ha generado más oportunidades de peligro. Si mantiene este ritmo, tiene alta probabilidad de anotar otro gol.',
  favorites_teams: 'Equipos',
  favorites_competitions: 'Competiciones',
  upcoming_matches: 'Próximos partidos',
  ia_placeholder: 'Escribe tu pregunta...',
  ia_quick_predictions: 'Predicciones',
  ia_quick_curious: 'Datos curiosos',
  ia_quick_analysis: 'Análisis rápido',
  ia_welcome: '¡Hola! Soy el asistente IA de FutHub. Pregúntame sobre partidos, estadísticas o predicciones.',
};
